### ISSUE TITLE
Sleep Screen Layout 2 | Master Checklist | Modify the layout of the final sleep screen image to have 4 pages, for the respected 4 days, composed along with top mini calendar

### ISSUE THREAD

**Issue by anti22dot** [anti22dot/rm_calendar_memo#25]
# **To set the context of this point**: 
* When the [`rm_calendar_memo` app](https://github.com/anti22dot/rm_calendar_memo) works, the scripts within this app would replace the `suspended.png` file of the RMPP with the custom file, which would be resized page of the PDF document on which we are working ( [this document](https://github.com/anti22dot/rm_calendar_memo/blob/main/rm_calendar/430f8cdf-e2e8-412c-b7e3-5ebf3b126bff.pdf) )
* Hence, the final image, which would be showed on the sleep screen of the RMPP, would be composed of the two parts: 
(1) PDF page-specific thumbnail
https://github.com/anti22dot/rm_calendar_memo/blob/c1879e2c361bee1c680159c013029c6ed64fc4b8/periodically_update_suspended_png.sh#L14
and (2) [mini calendar for the respected day (the day when scripts run)](https://github.com/anti22dot/rm_calendar_memo/tree/main/calendars)

# **IDEA for improvement**:
* Given the screen on the RMPP is relatively large, it is possible to lay out 4 PDF-specific notes pages on it.
* This way the sleep screen will become "even more powerful" , because it would show 4 pages of the PDF calendar, at the same time.
* In the PDF file , specifically for today's date (at the time of writing this memo - 04 Dec) there would be 3 dedicated pages, named "MORNING", "AFTERNOON" and "EVENING". And, inside the PDF file itself, the top calendar would show the date 04 Dec highlighted in black, for all of these 3 dedicated pages.
* At the same time, there is a particular page , that was just before the "MORNING" page of the 02 December in the PDF file. Those page is called "Week". And, for that particular page, the top calendar would show the entire week "in black".
* And, according to the future design of the sleep screen, when pressing power button, the sleep screen should show those layout that you have given above, and notes would be taken from that respected pages.
* And the left sidebar of the calendar in the PDF could have tabs which link to the Week, Morning, Afternoon, and Evening pages.

# Feature implementation plan:
- [x] anti22dot/rm_calendar#2
- [x] Create mockup sleep screen combined with 4 respected PDF pages, and see how it would look like. Find the best sizing for the resized images.
- [x] #41
- [x] #42
- [x] Test multiple different sets `Pen types | thickness | comfort of writing` on each of the 4 pages within the sleep screen properly.
- [x] Choose one particular set `Pen types | thickness | comfort of writing` as recommended to achieve the best visibility while not compromising too much with the comfort of writing.
- [x] anti22dot/rm_calendar#3
- [x] #31
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] anti22dot/rm_calendar#4
- [ ] anti22dot/rm_calendar#5
- [x] #38
- [ ] #39

NOTE: Kudos to @rudy0ne Person for this IDEA!
